package com.wixct.blogapi.jfinal.model;

import com.wixct.blogapi.jfinal.model.base.BaseAttach;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attach extends BaseAttach<Attach> {
	public static final Attach dao = new Attach().dao();
}
