package com.wixct.blogapi.jfinal.model;

import com.wixct.blogapi.jfinal.model.base.BaseComments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comments extends BaseComments<Comments> {
	public static final Comments dao = new Comments().dao();
}
