package com.wixct.blogapi.jfinal.model;

import com.wixct.blogapi.jfinal.model.base.BaseLogs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Logs extends BaseLogs<Logs> {
	public static final Logs dao = new Logs().dao();
}
