package com.wixct.blogapi.jfinal.model;

import com.wixct.blogapi.jfinal.model.base.BaseMetas;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Metas extends BaseMetas<Metas> {
	public static final Metas dao = new Metas().dao();
}
