package com.wixct.blogapi.jfinal.model;

import com.wixct.blogapi.jfinal.model.base.BaseOptions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Options extends BaseOptions<Options> {
	public static final Options dao = new Options().dao();
}
