package com.wixct.blogapi.jfinal.model;

import com.wixct.blogapi.jfinal.model.base.BaseRelationships;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Relationships extends BaseRelationships<Relationships> {
	public static final Relationships dao = new Relationships().dao();
}
