package com.wixct.blogapi.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUsers<M extends BaseUsers<M>> extends Model<M> implements IBean {

	public void setUid(java.lang.Long uid) {
		set("uid", uid);
	}
	
	public java.lang.Long getUid() {
		return getLong("uid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setHomeUrl(java.lang.String homeUrl) {
		set("home_url", homeUrl);
	}
	
	public java.lang.String getHomeUrl() {
		return getStr("home_url");
	}

	public void setScreenName(java.lang.String screenName) {
		set("screen_name", screenName);
	}
	
	public java.lang.String getScreenName() {
		return getStr("screen_name");
	}

	public void setCreated(java.lang.Long created) {
		set("created", created);
	}
	
	public java.lang.Long getCreated() {
		return getLong("created");
	}

	public void setActivated(java.lang.Long activated) {
		set("activated", activated);
	}
	
	public java.lang.Long getActivated() {
		return getLong("activated");
	}

	public void setLogged(java.lang.Long logged) {
		set("logged", logged);
	}
	
	public java.lang.Long getLogged() {
		return getLong("logged");
	}

	public void setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
	}
	
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}

}
