package com.wixct.blogapi.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttach<M extends BaseAttach<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setFname(java.lang.String fname) {
		set("fname", fname);
	}
	
	public java.lang.String getFname() {
		return getStr("fname");
	}

	public void setFtype(java.lang.String ftype) {
		set("ftype", ftype);
	}
	
	public java.lang.String getFtype() {
		return getStr("ftype");
	}

	public void setFkey(java.lang.String fkey) {
		set("fkey", fkey);
	}
	
	public java.lang.String getFkey() {
		return getStr("fkey");
	}

	public void setAuthorId(java.lang.Integer authorId) {
		set("author_id", authorId);
	}
	
	public java.lang.Integer getAuthorId() {
		return getInt("author_id");
	}

	public void setCreated(java.lang.Integer created) {
		set("created", created);
	}
	
	public java.lang.Integer getCreated() {
		return getInt("created");
	}

}
