package com.wixct.blogapi.jfinal.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRelationships<M extends BaseRelationships<M>> extends Model<M> implements IBean {

	public void setCid(java.lang.Long cid) {
		set("cid", cid);
	}
	
	public java.lang.Long getCid() {
		return getLong("cid");
	}

	public void setMid(java.lang.Long mid) {
		set("mid", mid);
	}
	
	public java.lang.Long getMid() {
		return getLong("mid");
	}

}
